apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: f.garrido-a.quesadas
  name: f.garrido-a.quesadas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f.garrido-a.quesadas
  template:
    metadata:
      labels:
        app: f.garrido-a.quesadas
    spec:
      containers:
        - image: franciscogarridocarrasco/f.garrido-a.quesadas:1.0.0
          name: fgarrido-aquesadas
          ports:
            - containerPort: 8881
          resources: {}
      restartPolicy: Always
