apiVersion: apps/v1
kind: Deployment
metadata:
  name: f.garrido-a.quesadas
  labels:
    app: f.garrido-a.quesadas
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: f.garrido-a.quesadas
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: f.garrido-a.quesadas
    spec:
      containers:
      - name: f.garrido-a.quesadasd
        image: franciscogarridocarrasco/f.garrido-a.quesadas:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        - name: grpc
          containerPort: 9999
          protocol: TCP
        command:
        - ./f.garrido-a.quesadas
        - --port=9898
        - --port-metrics=9797
        - --grpc-port=9999
        - --grpc-service-name=f.garrido-a.quesadas
        - --level=info
        - --random-delay=false
        - --random-error=false
        env:
        - name: f.garrido-a.quesadas_UI_COLOR
          value: "#34577c"
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/healthz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz
          initialDelaySeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2000m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
