apiVersion: v1
kind: Service
metadata: 
  name: mysql
  labels: 
    name: mysql
spec:
  ports:
    - name: jdbc
      port: 3306
      targetPort: 3306
  selector: 
    name: mysql
    version: "8"
  type: NodePort